- name: test_workflow
  uses: ${{ secrets.USER_NAME }}/github-action-ssh@release
  with:
    command: ls -a
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USER_NAME }}
    privateKey: ${{ secrets.PUBKEY }}