name: test_workflow

on: workflow_dispatch

jobs:
  mojito_server_test:
    runs-on: ubuntu-latest

    steps:
      - name: login ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY}}
          script_stop: true
          script: |
            cd /var/local
            ls -a